version: '3.8'

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:latest
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/examplepassword
    ports:
      - "7474:7474" # Neo4j HTTP felület
      - "7687:7687" # Neo4j Bolt protokoll a szkripteknek
