version: '3.8'

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    extra_hosts:
    - "host.docker.internal:host-gateway" 
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27018:27017"